[package]
name = "gorldle-front"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-net = "0.6.0"
log = { version = "0.4.25", features = ["serde", "std"] }
wasm-logger = "0.2.0"
yew = { version = "0.21.0", features = ["csr"] }
yew-router = "0.18.0"
